# Generated by Django 4.1 on 2023-04-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_myappuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamimage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='takım resim link'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamlogo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='logo link'),
        ),
    ]
