# Generated by Django 4.1 on 2023-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_teams_teamimage_alter_teams_teamlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamimage2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='takım resim2 link'),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamimage3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='takım resim3 link'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamimage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='takım resim1 link'),
        ),
    ]
